apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  namespace: awesome
spec:
  containers:
  - name: container1
    image: alpine:3.12.0
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /etc/a
  - name: container2
    image: alpine:3.12.0
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /etc/b
  volumes:
  - name: shared-data
    emptyDir: {}
